Repository bestksl/SSW695, pull requests merged in 2020-04, with the labels that each got.

#88 Fix validations
  hobbymatcher_sb/pom.xml
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/error/ErrorController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/event/EventController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/hobby/HobbyController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Blog.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Category.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Comment.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Event.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Hobby.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Review.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/User.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/handler/GlobalExceptionHandler.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/HobbyService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/BlogServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/EventServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/HobbyServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/ReviewServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/UserServiceImpl.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/EventDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/HobbyDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/ReviewDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/service/ReviewServiceTest.java
Labels: Back-End

#92 mh more hobbies&events
  documents/database-eer.mwb
  documents/database-eer.mwb.bak
  documents/database.sql
  hobbymatcher-ui/src/components/Footer.vue
  hobbymatcher-ui/src/components/Header.vue
  hobbymatcher-ui/src/components/blogs/BlogsList.vue
  hobbymatcher-ui/src/components/blogs/BlogsListing.vue
  hobbymatcher-ui/src/components/events/EventForm.vue
  hobbymatcher-ui/src/components/events/EventService.ts
  hobbymatcher-ui/src/components/events/EventView.vue
  hobbymatcher-ui/src/components/events/RecentEvents.vue
  hobbymatcher-ui/src/components/hobbies/HobbyForm.vue
  hobbymatcher-ui/src/components/hobbies/HobbyService.ts
  hobbymatcher-ui/src/components/hobbies/HobbyView.vue
  hobbymatcher-ui/src/components/search/FilterBar.vue
  hobbymatcher-ui/src/components/search/FilterCategories.vue
  hobbymatcher-ui/src/views/Events.vue
  hobbymatcher-ui/src/views/Hobbies.vue
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/event/EventController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/hobby/HobbyController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/EventDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/HobbyDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Comment.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Event.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/EventService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/HobbyService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/EventServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/HobbyServiceImpl.java
  hobbymatcher_sb/src/main/resources/mapper/EventDao.xml
  hobbymatcher_sb/src/main/resources/mapper/HobbyDao.xml
Labels: Back-End, Front-End, bugfix, database, enhancement

#97 Fix recom events
  hobbymatcher_sb/src/main/java/com/hobbymatcher/config/server/ResourceSeverConfig.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/event/EventController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/EventDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Event.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/EventService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/EventServiceImpl.java
  hobbymatcher_sb/src/main/resources/mapper/EventDao.xml
Labels: Back-End

#103 final bugfixes
  hobbymatcher-ui/.env.development
  hobbymatcher-ui/package-lock.json
  hobbymatcher-ui/package.json
  hobbymatcher-ui/src/components/Api.ts
  hobbymatcher-ui/src/components/Footer.vue
  hobbymatcher-ui/src/components/Header.vue
  hobbymatcher-ui/src/components/HelloWorld.vue
  hobbymatcher-ui/src/components/auth/AuthService.ts
  hobbymatcher-ui/src/components/auth/LoginForm.vue
  hobbymatcher-ui/src/components/auth/RegisterForm.vue
  hobbymatcher-ui/src/components/blogs/BlogView.vue
  hobbymatcher-ui/src/components/events/EventForm.vue
  hobbymatcher-ui/src/components/events/EventSearchResults.vue
  hobbymatcher-ui/src/components/events/EventThumb.vue
  hobbymatcher-ui/src/components/events/EventThumbs.vue
  hobbymatcher-ui/src/components/events/EventView.vue
  hobbymatcher-ui/src/components/events/GalleryEventThumb.vue
  hobbymatcher-ui/src/components/events/ManageParticipants.vue
  hobbymatcher-ui/src/components/events/RecentEvents.vue
  hobbymatcher-ui/src/components/hobbies/HobbyForm.vue
  hobbymatcher-ui/src/components/hobbies/HobbyService.ts
  hobbymatcher-ui/src/components/hobbies/HobbyThumb.vue
  hobbymatcher-ui/src/components/hobbies/HobbyThumbV2.vue
  hobbymatcher-ui/src/components/hobbies/HobbyThumbs.vue
  hobbymatcher-ui/src/components/hobbies/HobbyView.vue
  hobbymatcher-ui/src/components/reviews/CommentForm.vue
  hobbymatcher-ui/src/components/reviews/CommentView.vue
  hobbymatcher-ui/src/components/reviews/ReviewForm.vue
  hobbymatcher-ui/src/components/reviews/ReviewService.ts
  hobbymatcher-ui/src/components/reviews/ReviewView.vue
  hobbymatcher-ui/src/components/reviews/Reviews.vue
  hobbymatcher-ui/src/components/user/GeneralInformationForm.vue
  hobbymatcher-ui/src/components/user/UserBlogs.vue
  hobbymatcher-ui/src/components/user/UserEvents.vue
  hobbymatcher-ui/src/components/user/UserHobbies.vue
  hobbymatcher-ui/src/main.ts
  hobbymatcher-ui/src/views/CreateEvent.vue
  hobbymatcher-ui/src/views/EditEvent.vue
  hobbymatcher-ui/src/views/EditHobby.vue
  hobbymatcher-ui/src/views/Home.vue
  hobbymatcher-ui/src/views/Login.vue
  hobbymatcher-ui/src/views/Profile.vue
  hobbymatcher-ui/src/views/Register.vue
  hobbymatcher-ui/src/views/ViewBlog.vue
  hobbymatcher_sb/src/main/java/com/hobbymatcher/config/server/ResourceSeverConfig.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/blog/BlogController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/user/UserController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/BlogDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/BlogService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/BlogServiceImpl.java
  hobbymatcher_sb/src/main/resources/application.properties
  hobbymatcher_sb/src/main/resources/mapper/BlogDao.xml
Labels: Back-End, Front-End, bugfix

#105 updated diagrams, and fixed some bugs
  .DS_Store
  documents/class-diagram.jpg
  documents/database-eer.png
  hobbymatcher_sb/class-diagram.jpg
  hobbymatcher_sb/class-diagram.ucls
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/file/FileController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Event.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Hobby.java
Labels: bugfix

#108 clearing dummy data, redirect to login after register
  hobbymatcher-ui/src/components/auth/LoginForm.vue
  hobbymatcher-ui/src/components/auth/RegisterForm.vue
  hobbymatcher-ui/src/views/Register.vue
Labels: bugfix

#109 hide "write blog" button if no hobby is specified
  hobbymatcher-ui/src/views/Blogs.vue
Labels: Front-End, bugfix
