Repository bestksl/SSW695, pull requests merged in 2020-03, with the labels that each got.

#62 added validations
  hobbymatcher-ui/src/components/auth/SignInForm.vue
  hobbymatcher-ui/src/components/auth/SignUpForm.vue
  hobbymatcher-ui/src/components/events/EventForm.vue
  hobbymatcher-ui/src/components/hobbies/HobbyForm.vue
  hobbymatcher-ui/src/components/reviews/ReviewForm.vue
  hobbymatcher-ui/src/components/reviews/ReviewView.vue
  hobbymatcher-ui/src/views/Home.vue
Labels: Front-End

#65 connected addhobby back and frontned
  .gitignore
  hobbymatcher-ui/src/components/auth/AuthService.ts
  hobbymatcher-ui/src/components/hobbies/HobbyForm.vue
  hobbymatcher-ui/src/components/hobbies/HobbyService.ts
  hobbymatcher-ui/src/components/hobbies/HobbyThumb.vue
  hobbymatcher-ui/src/components/hobbies/HobbyThumbs.vue
  hobbymatcher-ui/src/components/hobbies/HobbyView.vue
  hobbymatcher-ui/src/views/Hobbies.vue
  hobbymatcher-ui/src/views/Home.vue
  hobbymatcher-ui/src/views/ViewHobby.vue
  hobbymatcher_sb/src/main/java/com/hobbymatcher/config/server/ResourceSeverConfig.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/file/FileController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/hobby/HobbyController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/util/FileUtil.java
  hobbymatcher_sb/src/main/resources/fileupload.properties
  hobbymatcher_sb/src/main/resources/fileupload.properties.example
  hobbymatcher_sb/src/main/resources/mapper/HobbyDao.xml
Labels: Back-End, Front-End

#69 added api to be tested, and fixed frontend hobby/event auth bug
  documents/api-tobe-tested.txt
  hobbymatcher-ui/src/components/Footer.vue
  hobbymatcher-ui/src/components/Header.vue
  hobbymatcher-ui/src/components/auth/AuthService.ts
  hobbymatcher-ui/src/components/auth/LoginForm.vue
  hobbymatcher-ui/src/views/CreateEvent.vue
  hobbymatcher-ui/src/views/CreateHobby.vue
Labels: Front-End, bugfix

#74 some bugfixes
  documents/database.sql
  documents/howto-run.txt
Labels: Back-End, bugfix, documentation

#83 finalized database structure, added user profile page (partially)
  documents/class-diagram.png
  documents/database-eer.mwb
  documents/database-eer.mwb.bak
  documents/database-eer.png
  documents/database.sql
  documents/domain_structure.PNG
  hobbymatcher-ui/src/components/Header.vue
  hobbymatcher-ui/src/components/user/GeneralInformation.ts
  hobbymatcher-ui/src/components/user/GeneralInformationForm.vue
  hobbymatcher-ui/src/components/user/ProfileService.ts
  hobbymatcher-ui/src/components/user/UserHobbies.vue
  hobbymatcher-ui/src/main.ts
  hobbymatcher-ui/src/router/index.ts
  hobbymatcher-ui/src/views/Profile.vue
  hobbymatcher_sb/src/main/java/com/hobbymatcher/authentication/filter/JwtRequestFilter.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/authentication/service/JwtUtilService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/auth/AuthController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/hobby/HobbyController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/user/UserController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/UserDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Hobby.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/User.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/UserService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/AuthUtilService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/BlogServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/CommentServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/UserServiceImpl.java
  hobbymatcher_sb/src/main/resources/mapper/HobbyDao.xml
  hobbymatcher_sb/src/main/resources/mapper/UserDao.xml
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/UserDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/service/UserServiceTest.java
Labels: Back-End, Front-End

#84 hobby follower and event subscription
  documents/database-eer.mwb
  documents/database-eer.mwb.bak
  documents/database-eer.png
  documents/database.sql
Labels: database

#85 Add review
  .DS_Store
  hobbymatcher_sb/pom.xml
  hobbymatcher_sb/src/main/java/com/hobbymatcher/config/server/ResourceSeverConfig.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/Review/ReviewController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/controller/blog/BlogController.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/CommentDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/dao/ReviewDao.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Comment.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/entity/Review.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/CommentService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/ReviewService.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/CommentServiceImpl.java
  hobbymatcher_sb/src/main/java/com/hobbymatcher/service/impl/ReviewServiceImpl.java
  hobbymatcher_sb/src/main/resources/application.properties
  hobbymatcher_sb/src/main/resources/mapper/CommentDao.xml
  hobbymatcher_sb/src/main/resources/mapper/ReviewDao.xml
  hobbymatcher_sb/src/main/resources/mapper/UserDao.xml
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/CategoryDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/EventDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/HobbyDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/ReviewDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/dao/UserDaoTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/service/EventServiceTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/service/ReviewServiceTest.java
  hobbymatcher_sb/src/test/java/com/hobbymatcher/service/UserServiceTest.java
Labels: Back-End

#86 changed the background color for body
  hobbymatcher-ui/src/App.vue
  hobbymatcher-ui/src/main.ts
  hobbymatcher-ui/src/views/Home.vue
Labels: Front-End
